type FragmentDetails = Record<string, { description: string }>

export const fragmentDetails:FragmentDetails = {
  fragment_1: { description: 'End of the World - path to the Abyss' },
  fragment_2: { description: 'Beneath the first throne in The Wasteland of the Fallen' },
  fragment_3: { description: 'Wasteland of the Fallen - Western Path: Rock Needles' },
  fragment_4: { description: 'Energy Crystal - Surface' },
  fragment_5: { description: 'Eastern Wall - Floor 5' },
  fragment_6: { description: 'Wasteland of the Fallen - Western Path: Sea of Dunes' },
  fragment_7: { description: 'Undersea Fortress - Deck D: Lower Matrix' },
  fragment_8: { description: 'Eastern Wall - Floor 2' },
  fragment_9: { description: 'Trail of Kings I' },
  fragment_10: { description: 'Energy Crystal - Surface' },
  fragment_11: { description: 'Trial of Kings II' },
  fragment_12: { description: 'End of the World - path to the Cosmos' },
  fragment_13: { description: 'The Forge - Southern Sector: Furnace Perimeter' },
  fragment_14: { description: "Heroes Rest - Cathedral Square: Decorative Gardens" }, 
  fragment_15: { description: 'Western Wall - Floor 4' },
  fragment_16: { description: "Heroes Rest - Underground Gallery: Western Floodgate" },
  fragment_17: { description: 'Eastern Wall - Floor 1 Gauntlet Fight' },
  fragment_18: { description: 'Eastern Wall - Floor 4' },
  fragment_19: { description: 'Wasteland of the Fallen - Western Path: Path of Damnation' },
  fragment_20: { description: "Avenger's Crypt: Library" },
  fragment_21: { description: "Avenger's Crypt: Suspension Bridges" },
  fragment_22: { description: 'Heroes Rest - Crypt of the Fake Knight: Library' },
  fragment_23: { description: 'Heroes Rest - Inner Perimeter: Path of Faith' },
  fragment_24: { description: "Heroes Rest - Cathedral Square: Decorative Gardens" },
  fragment_25: { description: 'Heroes Rest - Crypt of the Penitent: Terrace' },
  fragment_26: { description: "Heroes Rest - Collector's Lair"},
  fragment_27: { description: 'Wasteland of the Fallen - Western Path: Bone Marsh' },
  fragment_28: { description: 'Heroes Rest - Ancient Catacombs: Southern Drain' },
  fragment_29: { description: 'Undersea Fortress - Deck C: Magnetic Control' },
  fragment_30: { description: 'Western Wall - Floor 2' },
  fragment_31: { description: 'Heroes Rest - Ancient Catacombs: Southern Drain' },
  fragment_32: { description: 'Enigma XV - Bell Puzzle' },
  fragment_33: { description: 'Undersea Fortress - Deck B: Alternator' },
  fragment_34: { description: 'The Forge - Elder Forge: Western Corridor' },
  fragment_35: { description: 'The Cosmos: Zero Atmosphere: Bridge to the Stars' },
  fragment_36: { description: 'Tower of Light - Lower Section: First Lightsink' },
  fragment_37: { description: 'The Forge - Foundry: Western Furnace' },
  fragment_38: { description: 'The Cosmos - Lessek Corridor: Noctis System' },
  fragment_39: { description: 'Tower of Light - Upper Section: First Enhancer' },
  fragment_40: { description: 'Ascension Caves - Goblin Mines: Excavation' },
  fragment_41: { description: 'Tower of Light - Lower Section: Tower Base' },
  fragment_42: { description: 'Undersea Fortress - Deck B: Waste Power Plant' },
  fragment_43: { description: 'Royal Stairway - Road to Heaven: Sanctuaries' },
  fragment_44: { description: 'Aeterna Palace - Antechamber: Gate of the Kings ' },
  fragment_45: { description: 'Enigma XI' },
  fragment_46: { description: 'Tower of Light - Lower Section: Tower Base' },
  fragment_47: { description: 'Ascension Caves - Goblin Mines: Main Deposit' },
  fragment_48: { description: 'The Cosmos - Sea of Spheres: Glacial Belt' },
  fragment_49: { description: 'The Cosmos - Sivatra Sector: Ignis System' },
  fragment_50: { description: 'Ascension Caves - Goblin Mines: Main Deposit' },
  fragment_51: { description: 'Tower of Light - Side Chamber: Bishop Hall' },
  fragment_52: { description: 'Energy Crystal - Surface' },
  fragment_53: { description: 'Ascension Caves - Deep Tunnels: Waste Gallery' },
  fragment_54: { description: 'Ascension Caves - Abandoned Mine: Upper Rail Crossing' },
  fragment_55: { description: 'The Abyss - Denial: Weeping' },
  fragment_56: { description: 'Trial of the Kings VII' },
  fragment_57: { description: 'Trial of the Kings X' },
  fragment_58: { description: 'Aeterna Palace - Exterior of the Palace: West Wing' },
  fragment_59: { description: 'Trial of the Kings IX' },
  fragment_60: { description: 'Trial of the Kings VI' },
  fragment_61: { description: 'Energy Crystal - Surface' },
  fragment_62: { description: 'The Forge - Elder Forge: Western Corridor' },
  fragment_63: { description: 'The Forge - Steam Rooms: Southern Corridor' },
  fragment_64: { description: 'Ascension Caves - Central Tunnels: River Crossing' },
  fragment_65: { description: 'Ascension Caves - Deep Tunnels: Infested Breach' },
  fragment_66: { description: 'Trial of the Kings VIII' },
  fragment_67: { description: 'Trial of the Kings III' },
  fragment_68: { description: 'Wasteland of the Fallen - Western Path: Ash Cliff' },
  fragment_69: { description: 'Trial of the Kings V' },
  fragment_70: { description: 'Royal Stairway - Road to Heaven: Sovereign Islands' },
  fragment_71: { description: 'They Abyss - Acceptance: Serenity' },
  fragment_72: { description: 'The Force - Northern Sector: Furnace Permieter' },
  fragment_73: { description: 'Ascension Caves - Deep Tunnels: End of the Line' },
  fragment_74: { description: 'Trial of the Kings IV' },
  fragment_75: { description: 'The Forge: Main Chamber' },
}
